language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
install:
  - "pip install -q Django<$DJANGO_VERSION.99"
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "python manage.py test"
  - "python setup.py build_sphinx"
after_success:
  coveralls
